### PR TITLE
Issue #112: MailChimp field change to hidden.

### LINKED ISSUE #112: "Missing form label" in Tip Form (found with WAVE)
It looks like there is an extra hidden input field. Is this for a purpose?

### PR DESCRIPTION
**Pull request by brian-montgomery**
Fixes #112.

### CODE REVIEW

**Review by rachaelbradley — COMMENTED** [review]
This is a honeypot to keep down spam.  The solution should trick automatic bots into filling in the field so that mailchimp knows its fake and let humans generally avoid it and know what it is if they accidentially find it. To do that you need something like aria-label="honeypot, do not complete this field" and tabindex="-1" but don't completely hide it

**Review by alexisreytech — APPROVED** [review]
@brian-montgomery, I no longer see an alert/error from WAVE about the missing label for this field, so I think it resolved from the standpoint of not seeming to cause a problem for the automated test.

**Review by alexisreytech — CHANGES_REQUESTED** [review]
According to ARC Toolkit, there is an alert about the hidden field not having an autocomplete tag. If you add `autocomplete="off"` maybe that could be helpful?

**Review by alexisreytech — APPROVED** [review]

**Comment by brian-montgomery** [comment]
> According to ARC Toolkit, there is an alert about the hidden field not having an autocomplete tag. If you add `autocomplete="off"` maybe that could be helpful?

Perhaps, but let's see about that on another day. Let's ship it as is, for now.

**Pull request merged**
