### PR TITLE
Issue #209: Create "Tip of the Week" services page that Rachael can l…

### LINKED ISSUE #209: Add "Tip of the Week" page under services...
Include the registration form, as well as some the image Rachael is working on.

Make it like the mentoring page, which is at the top level, but is underneath "Services" in the breadcrumbs.

### PR DESCRIPTION
**Pull request by brian-montgomery**
…ink to.

Note: Still needs updated image from Rachael for the header.

Fixes #209

### CODE REVIEW

**Review by alexisreytech — CHANGES_REQUESTED** [review]
Overall, this page looks good, and I just have some small things to consider in Slack.

**Review by alexisreytech — COMMENTED** [review]
@brian-montgomery, the changes overall look good, although I did notice a couple other things:

- When viewing the page at 320 px wide by 256 px long, it looks like there is a horizontal scroll, as the page seems to be overflowing. However, the spacing within the article does look good.

- Consider capitalizing Tip of the Week for the following sentence: "Check out a previous tip of the week below."

**Comment by brian-montgomery** [comment]
> * When viewing the page at 320 px wide by 256 px long, it looks like there is a horizontal scroll, as the page seems to be overflowing. However, the spacing within the article does look good.

I'm not seeing that in either Chrome or Firefox. I'm not seeing where it's overflowing.

**Comment by alexisreytech** [comment]
> > * When viewing the page at 320 px wide by 256 px long, it looks like there is a horizontal scroll, as the page seems to be overflowing. However, the spacing within the article does look good.
> 
> I'm not seeing that in either Chrome or Firefox. I'm not seeing where it's overflowing.

@brian-montgomery, I apologize. I checked it again, and it looks fine.

**Review by alexisreytech — APPROVED** [review]

**Review by rachaelbradley — APPROVED** [review]
Change the image to the blue but otherwise, this looks good.

**Pull request merged**
