### PR TITLE
Staff and donate start

### LINKED ISSUE #15: Add links to staff pages
When working on #6, add links to LinkedIn, Facebook, Emails, etc to the board and staff profiles.
Add any necessary branding to it.

### PR DESCRIPTION
**Pull request by brian-montgomery**
Updating the staff pages with links for email, linkedin and other accounts.
Started establishing an updated version of the donation page.

To run this, you'll need to install the `astro-icon` library.

Fixes #15

### CODE REVIEW

**Comment by alexisreytech** [comment]
It looks like 'astro-icon' could not be found, so I needed to run the following command: npm i astro-icon

**Comment by alexisreytech** [comment]
On the "Donate" page, it might be helpful to have the links for PayPal and Stripe open in a separate tab.

**Review by alexisreytech — APPROVED** [review]
Looks good so far! Feel free to merge this with the main branch.

**Comment by brian-montgomery** [comment]
> It looks like 'astro-icon' could not be found, so I needed to run the following command: npm i astro-icon

Yep. I updated the top description to note the update.

**Pull request merged**
